package gui.measurementGUI;

import javafx.scene.control.Label;
import javafx.scene.control.Slider;
import javafx.scene.layout.VBox;
import measurements.Measurements;
import measurements.SliderData;

import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import gui.elements.SliderInterface;

/**
 * Here a slider is implemented that will be used to measure how productive you
 * are right now.
 * 
 * @author Mathieu
 * @version 08/23/2018
 */
public class Productivity implements SliderInterface {

	private static Measurements m;
	Slider slider;


	@Override
	public void actionSlider(int newValue) {
		System.out.println("value of the productivity slider " + newValue);
		m.addProductivity(new SliderData(newValue, LocalTime.now()));
	}

	/**
	 * @return VBox - a VBox with a question and a slider in it.
	 */
	public VBox prodSlider() {
		Label text = new Label("Hoe nuttig ben je nu bezig?");
		VBox temp = new VBox();
		slider = sliders();
		temp.getChildren().addAll(text, slider);
		return temp;
	}

	/**
	 * 
	 * @param obj - sets the right reference to save the data that is generated by
	 *            the used input
	 */
	public void setMeasurement(Measurements obj) {
		m = obj;
	}

	public void reset() {
		reset(slider);
	}


}
